@baseUrl = https://localhost:7192
@postId = 6738d332-2ed6-4f19-8fd9-7ea0a5957607
@deletePostId = 6738d332-2ed6-4f19-8fd9-7ea0a5957607

@tokenA = CfDJ8BKHkEPIFZxJlFDI7YlckWKuPiIMk-tOXkMTMGbl7YqkTD0ANhFI8wHe9BX_TDArMuz_Uj8tevGm6q2UzrY77KF65_QQD0QgB-_hBc_c52W4t3tPO4X-o3eFTjHir1RkH4bzA5VA8oaeXu8cRtryJpuaUzxjPDBRjNmuYBHJYmGytdh4OqN8LBelh-RkrNPV3GOLVOtDcy9eiR9aFGNydL_bLnZCk72KT1Dat06rrSKjRlbXakgPpOCg7sl8mO6_cm2Ixw3mR0zTlEnN9nq9OcvOIpgGqWBv4bKIG3hnu8dgpeZCC4n--tTC1ui64POfrlOPVigU2uZqw_hfOSZhhzOsEQDgKYSDMd10VNC2mfEeqYOP3cjGM5Y09mY3PEsCUfQeV9K-fAJSQ4afpuZhMTF-KhysD-2UeT8h4uFTup9khM6wgw4RdZNFoMvA8zco1hmRk5wQjpKb2v30q1aQj_hoxVNUnoRwb3EJlyf1DA1j7flE-nBxaBgkEc6CKEr1BXZ5pFdp-EjP54Chl_SL7od7tLCsUEfKMk6BDRsD3RWnARVN8cPu5ts7bsFHljtRGM7Cr42mOOyAML8VUrelYOg4YQqthzwimRW1wbZbcg9M4DwdktX-XRPoS9kTjrMWVLtq8Dg1-n22_fmCv7S2sG6oJI6qnz2g361xBoQw1wWSH8gWr-olHN67iWmh6XNeK8pYIN01lZHcp7CgiayuGFRf-WGCzzD6dlesRIaMohrS
@tokenB = CfDJ8BKHkEPIFZxJlFDI7YlckWIzjJWHOcYWjGmxHytOpbI2rtM9M_TcLYGP7JiIOF6DysQ4n9rXsW5ffn0R-9fCpGPBz6gJmkOm2wuw77cTdfP4AT_RNzC3z-VnJqNU0K3OPTwkypxSBK7z5fJWi9z3buNCEQI13udU39sFhymsDdw8kYpH30lLMS5rMu1T9zL052yOFwVprwyDH7XYhCvL5n_MtfBZ4IcJaK9wj5Vsyk8gmo1xbl-51gLy8s3upP-uieknSnwKmjv8nSXeOB4Wb5AQdxNFOWyLdCNlzxbv0ZDaIuHylVcKzO4hgm0VR6lyf636c_sekVNxpbx343Jdb_YlyYs4MVSRjr8a7-DACkw5tgc4WHh91NrxFyEWvT6s7-of8A6x85GTtG2LrRXWkevnVfSTgzoYYhfd7Hwe6iOf90zkB48pn368KxoUpIXErfs5uvDiZoIXXWVd3KznbIdb2NDG0h7piAa2Ku8hoG4EJi0PgCZlYaAg_6dAYlSf50VboDEqnRqrciksEAOKZIsi3PIAyVk39rsRhuYznFDjBUAoSHz_iXKf3l7gSSnEXwDpGVQu-4jJ5xq4Pka6_wIfz2JPiAZNQ4NXPwDExG_kK9hhWcqqhRYusGaqOtzUvHAzJO9T8Zu8MkC24k7KpBKxPwMtwFrbBtw7SzitaJCiQaaI4OYNXvSCEybgHftazUSHnT8pR8VI_ybmwQ8qNa1S880m56siTdykPcNqJvqR
@postId = df5dec04-3960-4455-95da-83aa9df4cd24


### Tao bai viet
POST {{baseUrl}}/api/posts
Content-Type: application/json

{
  "authorId": "11111111-1111-1111-1111-111111111111",
  "content": "Bài viết đầu tiên của tôi!"
}

### Kiem tra ket noi PostgreSQL
GET {{baseUrl}}/dev/database

### Doc bai viet theo ID
GET {{baseUrl}}/api/posts/{{postId}}

### Trang 1, moi trang 2 bai
GET {{baseUrl}}/api/posts?pageNumber=1&pageSize=2

### Trang 2, moi trang 2 bai
GET {{baseUrl}}/api/posts?pageNumber=2&pageSize=2

### So trang khong hop le
GET {{baseUrl}}/api/posts?pageNumber=0&pageSize=2

### So bai moi trang vuot gioi han
GET {{baseUrl}}/api/posts?pageNumber=1&pageSize=51

### Sua noi dung bai viet
PUT {{baseUrl}}/api/posts/{{postId}}/content
Content-Type: application/json

{
  "content": "Tôi vừa cập nhật nội dung bài viết!"
}

### Doc lai bai viet sau khi sua
GET {{baseUrl}}/api/posts/{{postId}}

### Xem bai viet truoc khi xoa
GET {{baseUrl}}/api/posts/{{deletePostId}}

### Xoa bai viet
DELETE {{baseUrl}}/api/posts/{{deletePostId}}

### Kiem tra sau khi xoa
GET {{baseUrl}}/api/posts/{{deletePostId}}



### Create
POST {{baseUrl}}/api/posts
Authorization: Bearer {{tokenA}}
Content-Type: application/json

{
  "content": "Bài viết của tài khoản A."
}

### Update
PUT {{baseUrl}}/api/posts/{{postId}}/content
Authorization: Bearer {{tokenA}}
Content-Type: application/json

{
  "content": "Nội dung do A thử thay đổi."
}

### Delete
DELETE {{baseUrl}}/api/posts/{{postId}}
Authorization: Bearer {{tokenB}}

### Doc lai bai de kiem tra
GET {{baseUrl}}/api/posts/{{postId}}

### B binh luan vao bai cua A
POST {{baseUrl}}/api/posts/{{postId}}/comments
Authorization: Bearer {{tokenB}}
Content-Type: application/json

{
  "content": "Đây là bình luận đầu tiên của tôi!"
}