@baseUrl = https://localhost:7192
@postId = 6738d332-2ed6-4f19-8fd9-7ea0a5957607
@deletePostId = 6738d332-2ed6-4f19-8fd9-7ea0a5957607

@tokenA = CfDJ8BKHkEPIFZxJlFDI7YlckWIN3fQ7iY8OffwI5bMCYKO0S980S5gJU_9z6auieiaOPJgp52gaRGr3szNKX5e5YFTdh-wcrNnEnbp_JdsDzL1HhYZIk4YPbDp4R79wM78xbWVdxKlRRx-6NqLgbbfPDGGdGeGoWS38TNbFUiFfYuMOHeSxUd9UW9DXgAdtnR_dZhY_-zn71ShqayPJcAifUXbhB-_2GBRUM5m0MwwEv9MiREoW8are8xvWS3UEGAktpgk_wFjLqRfVsrJx9PFuSnnW2uW7tBuFr7w9l829p1_Wnzn8ZeZSKGeSh2oTslk65EgqDuPznfMFVCUdLVA9we0Zg8bfTAfVYFwBsQ2MxSSxJ1m9SpiuKnKl6oDjMiZgh0iZa4jq0QJITLDSQJFxmx-9PzP6lgaiu8lC9XcNAChisz7nkUvSZV5vF3oU_Qo_u2Mpdh0rMQfbgGJYlD9z9y2qRUK7WkOV3Ev4NKW7lrMi4obXLlRtsqaRKGQpFeinnwNx6oKBvmZW9YLpJoOYV33FM2tEZohmJnnczUCF8nYf3AaCKBMlaFMuiG7I46E-0fank3VGcqqUGMWdBEvex9Q9e19Judk4sN4_qhxke431b7AsB732CCuWGHf7o1FL962HqcFyB3I8vG4B4Sw6L1SSxC1hsZzZqINlAVDRWRTu2lO5vkyCF2IuIiYHHPxHzSdgnydCrbtYeFhUZFFtl_mAPCYCVLYYVrg1lyC3oeVa
@tokenB = CfDJ8BKHkEPIFZxJlFDI7YlckWKji9wkKC0jGq7FhxTaHytwSFfMxgn98Vq_mkMiAgI9k70PUB2os6GUcV71VIk6KV35LBx7TpcrUb-3DKqRSIsjmySdNgsqWrc_8aydb783MnOjmv_OLKcE4w-JxwryN5GaWLhOtgTeFEYAFZz4J7U8Tx8Wvj5oOpbI9PbZp-bUrVoA0CiyscJT5B5aarpWWZfb3N_SW5hnyrwT9gVrf54gdqe9Hfqv2eOCMlDLwVoiUhGjqHukLBfN_HAlsFuBM013E8K6PWeFRB17m7A_XZtOQ3r27QR8NDZv5ktqB92YQ-KT7FCs3iXtsaBbutaVrSuqhy6TDm_lrWQGbsA4xOidkzAxSEgmu5iAyKzRk_1Qa5IqRwJYzW_rq4_WnAOAC3BfNMNzuUpevyDRdrjaWfOaUe0nsruyxb0zFYPaL-JTAvCs1d1Lsfi9qak9noZyGvulb8XVzV_nYKpu_73Xlf4_NoahNLRimNuFsKCDjs78Jlo1i59CPzpSK7Ldib84EfbSwsgJ53JiALOgw2uW0jBsq0ZPis7TVsRCrwIz42xdjSMKHyVn1H3o6jc90-4gE_xaHmq4SmfHacG-rrlimR20tsAiYxTZGz8NakLQLGGBKkKCqFuzDjok73xuCljYlosdpvYsTzWcjVWLJV-VAD3IGAYsOMFVsS1tvm3MigRPG_XMEmmqs0rG-f3fYcSqhrO1EGo7zrhMDA67QXfmR-qf
@postId = df5dec04-3960-4455-95da-83aa9df4cd24


### Tao bai viet
POST {{baseUrl}}/api/posts
Content-Type: application/json

{
  "authorId": "11111111-1111-1111-1111-111111111111",
  "content": "Bài viết đầu tiên của tôi!"
}

### Kiem tra ket noi PostgreSQL
GET {{baseUrl}}/dev/database

### Doc bai viet theo ID
GET {{baseUrl}}/api/posts/{{postId}}

### Trang 1, moi trang 2 bai
GET {{baseUrl}}/api/posts?pageNumber=1&pageSize=2

### Trang 2, moi trang 2 bai
GET {{baseUrl}}/api/posts?pageNumber=2&pageSize=2

### So trang khong hop le
GET {{baseUrl}}/api/posts?pageNumber=0&pageSize=2

### So bai moi trang vuot gioi han
GET {{baseUrl}}/api/posts?pageNumber=1&pageSize=51

### Sua noi dung bai viet
PUT {{baseUrl}}/api/posts/{{postId}}/content
Content-Type: application/json

{
  "content": "Tôi vừa cập nhật nội dung bài viết!"
}

### Doc lai bai viet sau khi sua
GET {{baseUrl}}/api/posts/{{postId}}

### Xem bai viet truoc khi xoa
GET {{baseUrl}}/api/posts/{{deletePostId}}

### Xoa bai viet
DELETE {{baseUrl}}/api/posts/{{deletePostId}}

### Kiem tra sau khi xoa
GET {{baseUrl}}/api/posts/{{deletePostId}}



### Create
POST {{baseUrl}}/api/posts
Authorization: Bearer {{tokenA}}
Content-Type: application/json

{
  "content": "Bài viết của tài khoản A."
}

### Update
PUT {{baseUrl}}/api/posts/{{postId}}/content
Authorization: Bearer {{tokenA}}
Content-Type: application/json

{
  "content": "Nội dung do A thử thay đổi."
}

### Delete
DELETE {{baseUrl}}/api/posts/{{postId}}
Authorization: Bearer {{tokenB}}

### Doc lai bai de kiem tra
GET {{baseUrl}}/api/posts/{{postId}}